add publish to chimps in workflow

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -1,10 +1,11 @@
-name: Publish release to NPM and GitHub Packages
+name: Publish release to NPM, GitHub & Chimps Packages
 
 on:
   release:
     types: published
     branches:
       - "main"
+  workflow_dispatch:
 
 permissions:
   id-token: write # Required for OIDC
@@ -25,7 +26,7 @@ jobs:
       - run: |
           ((npm publish --provenance --access public 2> /dev/null) | grep "@ryupold/vode@" > version.txt) || echo "...done"
           NEWVERSION=$(cat version.txt)
-          if [[ $NEWVERSION == *"npm error 409 Conflict"* || $NEWVERSION == *"@ryupold/vode@"* ]]; then
+          if [[ $NEWVERSION == *"409 Conflict"* || $NEWVERSION == *"@ryupold/vode@"* ]]; then
             echo "...success: $NEWVERSION"
           else
             echo "...failed to publish"
@@ -39,7 +40,7 @@ jobs:
       - run: |
           ((npm publish --access public 2> /dev/null) | grep "@ryupold/vode@" > version.txt) || echo "...done"
           NEWVERSION=$(cat version.txt)
-          if [[ $NEWVERSION == *"npm error 409 Conflict"* || $NEWVERSION == *"@ryupold/vode@"* ]]; then
+          if [[ $NEWVERSION == *"409 Conflict"* || $NEWVERSION == *"@ryupold/vode@"* ]]; then
             echo "...success: $NEWVERSION"
           else
             echo "...failed to publish"
@@ -47,3 +48,16 @@ jobs:
           fi
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - uses: oven-sh/setup-bun@v2
+      - run: |
+          cp .github/workflows/bunfig.toml bunfig.toml
+          ((bun publish --token="$CHIMPS_TOKEN" 2> /dev/null) | grep "@ryupold/vode@" > version.txt) || echo "...done"
+          NEWVERSION=$(cat version.txt)
+          if [[ $NEWVERSION == *"409 Conflict"* || $NEWVERSION == *"@ryupold/vode@"* ]]; then
+            echo "...success: $NEWVERSION"
+          else
+            echo "...failed to publish"
+            exit 1
+          fi
+        env:
+          CHIMPS_TOKEN: ${{ secrets.CHIMPS_TOKEN }}
